### ISSUE TITLE
[Task] 회원 - 채팅

### ISSUE THREAD

**Issue by oyeon-kwon** [codestates/bodysign-frontend#12]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 트레이너와 메시지 주고 받는 페이지 (Member_chat, Member_diet)

### TODO
1. [x] 메세지 주고 받기
2. [x] 이미지 주고 받기
2. [ ] 공지사항 보기
3. [x] 갤러리 보관함 (다중 삭제 가능)
