### ISSUE TITLE
[Task] 트레이너 - 회원 관리

### ISSUE THREAD

**Issue by oyeon-kwon** [codestates/bodysign-frontend#15]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 회원 관리 페이지 (Manage_Member)

### TODO
1. [x] manage-member 레이아웃
2. [x] existing-member 레이아웃
3. [x] 로직 변경: 새로운 회원, 가입된 회원 추가
4. [x] 회원 추가 API
5. [x] 회원 삭제 API
6. [x] 새로운 회원 추가 API
7. [x] 카테고리 추가 API
8. [x] 채팅방 라우팅
9. [ ] 채팅방 새로운 메시지 확인 API
