### ISSUE TITLE
[Task] 트레이너 - 회원: 회원 정보

### ISSUE THREAD

**Issue by oyeon-kwon** [codestates/bodysign-frontend#16]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 회원 정보 읽기 페이지

### TODO
1. [x] [emailId]-info 레이아웃
2. [x] [emailId]-inbody 레이아웃
3. [x] 졸업 유무 변경 API
4. [x] 회원 카테고리 변경 API
5. [x] 세션 추가 API
