### ISSUE TITLE
[Task] Home - 회원가입

### ISSUE THREAD

**Issue by oyeon-kwon** [codestates/bodysign-frontend#2]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 회원가입 기능 구현

### TODO
1. [x] signup 레이아웃
2. [x] 유효성 검사
3. [x] 트레이너 or 유저 버튼 => 토글 
4. [x] 트레이너로 가입할 때 관심사를 선택하는 인풋 추가
5. [x] Sign up API

### `3h`
