### ISSUE TITLE
[Task] 트레이너 - 회원(Back)

### ISSUE THREAD

**Issue by Hsource39** [codestates/bodysign-frontend#28]
### ISSUE
- Group:  `server`
- Type: `feature`
- Detail: 트레이너 - 회원 api 구현

### TODO
1. [ ] 회원 리스트 응답
2. [ ] 회원 / 카테고리 추가
3. [ ] 회원 삭제
4. [ ] 졸업 회원 리스트 응답
