### ISSUE TITLE
[Task] BackEnd Setup

### ISSUE THREAD

**Issue by Hsource39** [codestates/bodysign-frontend#3]
### ISSUE
- Group:  server
- Type: `feature`
- Detail: 백엔드 환경 셋업

### TODO
1. [ ] nest.js 를 이용해 셋업 만들기
2. [ ] Hot Reload 를 이용해 자동 서버 새로고침 확인
3. [ ] 실제로 서버 작동되는지 확인

### Estimated time
> Pick one
