### ISSUE TITLE
[Task] 트레이너 - 메뉴

### ISSUE THREAD

**Issue by sooe2min** [codestates/bodysign-frontend#36]
### ISSUE
- Group:  `client`, `server`, `sr`
- Type: `bug`, `feature`, `delete`
- Detail: fix actions from client redux

### TODO
1. [x] menu 레이아웃 
2. [x] myinfo 레이아웃
3. [x] sales(매출) 레이아웃
4. [x] ledger(정산) 레이아웃
5. [x] 기간별 조회 로직 구현
6. [x] 비밀번호 변경 API
7. [x] 정보 수정 API
8. [x] 탈퇴 API

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 1h`
- Group : `client`
- Sprint: `Sprint__NUMBER__`
- Urgency: `Middle`
