### ISSUE TITLE
[Task] DB Entity - Session, SessionExercise 정의

### ISSUE THREAD

**Issue by Jaeja-Phil** [codestates/bodysign-frontend#52]
### ISSUE
- Group:  `server`
- Type: `feature`
- Detail: Session, SessionExercise 엔티티 정의 및 관계확인

### TODO
1. [ ] Session, SessionExercise 엔티티 정의
2. [ ] 더 목적에 맞는 이름이 있는지 고려하여 필요시 이름 재정의
3. [ ] 스키마 검증 및 확인
