### ISSUE TITLE
[Task] GraphQL 셋업

### ISSUE THREAD

**Issue by Jaeja-Phil** [codestates/bodysign-frontend#53]
### ISSUE
- Group:  `server`
- Type: `feature`
- Detail: GraphQL 셋업 및 사용가능한 gql 설계

### TODO
1. [ ] GraphQL 셋업 및 사용가능한 gql 설계
2. [ ] Join테이블까지 반드시 확인.
3. [ ] 실제 사용된 쿼리 검증 (로그에 사용된 쿼리가 찍힐것으로 추정, 안찍힌다면 configuration에서 옵션으로 존재할것으로 추정)
