### ISSUE TITLE
[Task] Home - 회원가입(Back)

### ISSUE THREAD

**Issue by Hsource39** [codestates/bodysign-frontend#7]
### ISSUE
- Group:  `server`
- Type: `feature`
- Detail: 회원가입 서버부분

### TODO
1. [ ] 회원 아이디 유효성 검사
2. [ ] 회원 휴대폰번호 유효성 검사
3. [ ] 회원 비밀번호 유효성 검사
