### ISSUE TITLE
[Task] [Misc] 버그 수정

### ISSUE THREAD

**Issue by Jaeja-Phil** [codestates/bodysign-frontend#88]
### ISSUE
- Group:  `server`
- Type: `bug`
- Detail: 버그 리포트 수정

### TODO
User
- [x] interest 필드 추가
- [x] bulk 형태의 삭제 (status 변경)
- [x] updateUserInput 수정 (trainerId, userCategoryId, graduate 추가)

NonRegisteredUser
- [x] graduate 필드 추가
- [x] userCategoryId 필드 추가 및 relation 생성

ExerciseCategory
- [x] bulk 형태의 삭제

Chat
- [x] update, remove 추가

SessionHistory
- [x] commission 오타 수정

Session
- [x] order와 status를 추가한 조회 쿼리
- [x] feedback 완성 유무 필드 (sentFeedback)
- [x] 수업 완료 유무 필드 (completeSession)
- [x] date, createdAt, updatedAt 필드 추가
- [x] create시 date 추가
- [x] update시 수업완료, 피드백완료 필요
- [x] user, trainer ResolveField 제공

SessionExercise
- [x] SessionExerciseVolume 테이블 추가
- [x] updateSessionExercise 삭제

Trainer
- [x] userCategory, user 위한 ResolveField 제공
- [x] 전화번호 검색 graphql 쿼리 추가
